{{- if and .Values.keystore.enabled (eq .Values.keystore.type "secret") }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.keystore.name }}
  {{- if .Values.namespace.enabled }}
  namespace: {{ .Values.namespace.name }}
  {{- end }}
type: Opaque
stringData:
  {{- range $key, $value := .Values.keystore.data }}
  {{ $key }}: {{ $value | nindent 4 }}
  {{- end }}
{{- end }}
